### ISSUE TITLE
Production configuration

### ISSUE THREAD

**Issue by bassjacob** [bassjacob/stucco#2]
Should this tool support production bundling as well? It may be a departure from the tools usefulness, but I suppose erring on the side of a webpack.production.js with the same K/V as the development configuration would at least mean the bundle can be used on pages.

Given the intention to work on a distributed rendering platform rather than distributing modules directly, does it make sense to bundle that work as part of this tool?

**Comment by subshad** [comment]
Initially I'm going to add a webpack.production.js with the same settings as the development config, and then revisit when I'm ready to undertake a distributed model.
